<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SecondBrain.Core/SecondBrain.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" />
    <PackageReference Include="Ulid" />
  </ItemGroup>
</Project>
