<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>brain</AssemblyName>
    <RestoreEnablePackagePruning>false</RestoreEnablePackagePruning>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../SecondBrain.Core/SecondBrain.Core.csproj" />
    <ProjectReference Include="../SecondBrain.Infrastructure/SecondBrain.Infrastructure.csproj" />
    <ProjectReference Include="../SecondBrain.Storage/SecondBrain.Storage.csproj" />
    <ProjectReference Include="../SecondBrain.Server/SecondBrain.Server.csproj" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
