<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>brain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SecondBrain.Core/SecondBrain.Core.csproj" />
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
