<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="Ulid" />
  </ItemGroup>
</Project>
